### ISSUE TITLE
java.lang.VerifyError: Stack map does not match the one at exception handler

### ISSUE THREAD

**Issue by vektory79** [Devexperts/aprof#7] opened 2017-05-29 16:29 UTC
I try to run aprof with Wildfly 8 (custom build, but does'nt matter). In short time after start Wildfly crash with message:
```
  [wildfly] =========================================================================
  [wildfly] 
  [wildfly]   JBoss Bootstrap Environment
  [wildfly] 
  [wildfly]   JBOSS_HOME: /media/data/Java/ws/jboss/tst/2/jboss-bas-8.2.1.krista20
  [wildfly] 
  [wildfly]   JAVA: /usr/lib/jvm/java-8-oracle/bin/java
  [wildfly] 
  [wildfly]   JAVA_OPTS:  -server -XX:+UseCompressedOops  -server -XX:+UseCompressedOops -Xbootclasspath/a:/media/data/Java/ws/jboss/tst/2/lib/asm-analysis.jar:/media/data/Java/ws/jboss/tst/2/lib/asm-commons.jar:/media/data/Java/ws/jboss/tst/2/lib/asm-tree.jar:/media/data/Java/ws/jboss/tst/2/lib/asm-util.jar:/media/data/Java/ws/jboss/tst/2/lib/asm.jar:/media/data/Java/ws/jboss/tst/2/lib/selftest.jar:/media/data/Java/ws/jboss/tst/2/lib/transformer.jar -javaagent:/media/data/Java/ws/jboss/tst/2/aprof.jar -Xms128m -Xmx1g -Djava.awt.headless=true -XX:NativeMemoryTracking=summary -Dru.krista.core.audit.storage.folder.src.sca=/media/data/Java/ws/jboss/tst/2/dir1 -Dru.krista.core.audit.storage.folder.dst.sca=/media/data/Java/ws/jboss/tst/2/dir2
  [wildfly] 
  [wildfly] =========================================================================
  [wildfly] 
  [wildfly] 2017-05-29T19:18:45.922+0300: aprof: Loading Aprof 31, Copyright (C) 2002-2017 Devexperts LLC...
  [wildfly] 2017-05-29T19:18:53.239+0300: aprof: Writing dump to file aprof.txt...
  [wildfly] 2017-05-29T19:18:53.754+0300: aprof: Writing dump to file aprof.txt... done
  [wildfly] 2017-05-29T19:18:53.813+0300: aprof: Loaded in 7846 ms with 6806 ms in transformer (1040 ms other)
  [wildfly] 19:18:56,171 INFO  [org.jboss.modules] (main) JBoss Modules version 1.3.3.Final
  [wildfly] java.lang.VerifyError: Stack map does not match the one at exception handler 40
  [wildfly] 2017-05-29T19:18:56.769+0300: aprof: Shutting down...Exception Details:
  [wildfly] 2017-05-29T19:18:56.770+0300: aprof: Writing dump to file aprof.txt...
  [wildfly] 
  [wildfly]   Location:
  [wildfly]     org/jboss/as/server/BootstrapImpl$ShutdownHook.<init>()V @40: astore_2
  [wildfly]   Reason:
  [wildfly]     Current frame's flags are not assignable to stack map frame's.
  [wildfly]   Current Frame:
  [wildfly]     bci: @20
  [wildfly]     flags: { flagThisUninit }
  [wildfly]     locals: { uninitializedThis, 'com/devexperts/aprof/LocationStack' }
  [wildfly]     stack: { 'java/lang/Throwable' }
  [wildfly]   Stackmap Frame:
  [wildfly]     bci: @40
  [wildfly]     flags: { }
  [wildfly]     locals: { top, 'com/devexperts/aprof/LocationStack' }
  [wildfly]     stack: { 'java/lang/Throwable' }
  [wildfly]   Bytecode:
  [wildfly]     0x0000000: 014c 2a2b 59c7 0009 57b8 008c 594c 111a
  [wildfly]     0x0000010: 46b6 008f b700 042b 59c7 0009 57b8 008c
  [wildfly]     0x0000020: 594c b600 92a7 0014 4d2b 59c7 0009 57b8
  [wildfly]     0x0000030: 008c 594c b600 922c bfb1               
  [wildfly]   Exception Handler Table:
  [wildfly]     bci [20, 23] => handler: 40
  [wildfly]   Stackmap Table:
  [wildfly]     full_frame(@14,{UninitializedThis,Object[#136]},{UninitializedThis,Object[#136]})
  [wildfly]     full_frame(@34,{Object[#27],Object[#136]},{Object[#136]})
  [wildfly]     full_frame(@40,{Top,Object[#136]},{Object[#49]})
  [wildfly]     full_frame(@52,{Top,Object[#136],Object[#49]},{Object[#136]})
  [wildfly]     full_frame(@57,{Object[#27],Object[#136]},{})
  [wildfly] 
  [wildfly]     at com.devexperts.aprof.AProfSizeUtil.getObjectSizeByClass(AProfSizeUtil.java:106)
  [wildfly]     at com.devexperts.aprof.AProfOps.allocateSize(AProfOps.java:45)
  [wildfly]     at org.jboss.as.server.BootstrapImpl.<init>(BootstrapImpl.java:60)
  [wildfly]     at org.jboss.as.server.Bootstrap$Factory.newInstance(Bootstrap.java:236)
  [wildfly]     at org.jboss.as.server.Main.main(Main.java:96)
  [wildfly]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  [wildfly]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  [wildfly]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [wildfly]     at java.lang.reflect.Method.invoke(Method.java:498)
  [wildfly]     at org.jboss.modules.Module.run(Module.java:312)
  [wildfly]     at org.jboss.modules.Main.main(Main.java:460)
  [wildfly] 2017-05-29T19:18:57.234+0300: aprof: Writing dump to file aprof.txt... done
  [wildfly] 2017-05-29T19:18:57.234+0300: aprof: Stopped after 3470 ms with 2331 ms in transformer (1139 ms other)
  [wildfly] Result: 1
```

It's sad, but it's not so easy to start Wildfly with aprof due to JBoss Modules system. But I have write some scripts to prepare and run Widlfy with aprof integration. I will attach it latter.

**Comment by vektory79** [comment] 2017-05-29 19:44
I make the [with scripts](https://github.com/vektory79/wildfly-test-stand) to demonstrate the issue.

**Comment by tsitelov** [comment] 2017-05-31 22:40
Thank you for the report. We'll try to investigate it a bit later.

**Comment by tsitelov** [comment] 2017-09-06 17:44
We believe the issue is fixed in v32.

**Closed by tsitelov** 2017-09-06 17:44 UTC
